// <auto-generated />
using System;
using ImportAPIExcel.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ImportAPIExcel.Migrations
{
    [DbContext(typeof(ImportExcelContext))]
    [Migration("20210902111228_3-Add_Table_Lote")]
    partial class _3Add_Table_Lote
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ImportAPIExcel.Model.ExcelFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoteRefId")
                        .HasColumnType("int");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LoteRefId");

                    b.ToTable("ExcelFiles");
                });

            modelBuilder.Entity("ImportAPIExcel.Model.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataImportacao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Lote");
                });

            modelBuilder.Entity("ImportAPIExcel.Model.ExcelFile", b =>
                {
                    b.HasOne("ImportAPIExcel.Model.Lote", "Lote")
                        .WithMany("arquivos")
                        .HasForeignKey("LoteRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("ImportAPIExcel.Model.Lote", b =>
                {
                    b.Navigation("arquivos");
                });
#pragma warning restore 612, 618
        }
    }
}
